### ISSUE TITLE
Asunto: Ayuda

### ISSUE THREAD

**Issue by Montaner32** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-Montaner32#1]
` dev.new(); par(mfrow=c(4,6));
sapply(
  colnames(proved[sapply(proved,is.numeric)]),
  function(x) {
    hist(proved[,x], main=x)
    qqnorm(proved[,x], main=x)
    qqline(proved[,x])
  }
)´
`Error in hist.default(proved[, x], main = x) : 'x' must be numeric´
@geofis

**Comment by geofis** [comment]
Si pudieses imprimir en pantalla `proved`, podría ayudarte entonces, porque necesito saber qué contiene dicho objeto.
