### ISSUE TITLE
No Match

### ISSUE THREAD

**Issue by Montaner32** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-Montaner32#2]
`match(attr(proved.w.W$neighbours, "region.id"),proved$TOPONIMIA)==1:32
 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA`

pero, si pongo la sentencia:
` match(attr(proved.w.W$neighbours, "region.id"),proved$PROV)==1:32
 [1]   NA   NA   NA   NA   NA   NA   NA   NA   NA TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[21] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE`

@geofis

**Comment by geofis** [comment]
Imagino que hay algún inconveniente con los nombres de las regiones en el objeto de pesos. Prueba a imprimir

```
attr(proved.w.W$neighbours, "region.id")
```

Y también imprime a:

```
proved$TOPONIMIA
```

Deberían ser iguales, y seguramente no lo son. Para hacer que las regiones tengan atributos en el objeto de pesos, previamente debieron tenerlos en el objeto de vecinos. Si no le asignaste nombres a las regiones del objeto de vecinos, verifica arriba si ejecutaste una sentencia tal que:

```
attr(proved.nb, "region.id") <- proved$TOPONIMIA
```

Cuando hagas eso, crea de nuevo el objeto de pesos desde el de vecinos actualizado y debería haber match.
